#use_frameworks!

platform :ios, '11.0'

target 'No1SdkPod' do

  prefix = "./No1SdkLib/node_modules/react-native"

  pod 'FBLazyVector', :path => "#{prefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{prefix}/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{prefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{prefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{prefix}/"
  pod 'React-Core', :path => "#{prefix}/"
  pod 'React-CoreModules', :path => "#{prefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{prefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{prefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{prefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{prefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{prefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{prefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{prefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{prefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{prefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{prefix}/"

  pod 'React-cxxreact', :path => "#{prefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{prefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{prefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{prefix}/ReactCommon/jsinspector"
  pod 'React-callinvoker', :path => "#{prefix}/ReactCommon/callinvoker"
  pod 'React-runtimeexecutor', :path => "#{prefix}/ReactCommon/runtimeexecutor"
  pod 'React-perflogger', :path => "#{prefix}/ReactCommon/reactperflogger"
  pod 'React-logger', :path => "#{prefix}/ReactCommon/logger"
  pod 'ReactCommon/turbomodule/core', :path => "#{prefix}/ReactCommon"
  pod 'Yoga', :path => "#{prefix}/ReactCommon/yoga", :modular_headers => true

  pod 'DoubleConversion', :podspec => "#{prefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{prefix}/third-party-podspecs/glog.podspec"
  pod 'boost', :podspec => "#{prefix}/third-party-podspecs/boost.podspec"
  pod 'RCT-Folly', :podspec => "#{prefix}/third-party-podspecs/RCT-Folly.podspec"
  
#  pod 'react-native-safe-area-context', :podspec => "#{prefix}/../react-native-safe-area-context/react-native-safe-area-context.podspec"
#  pod 'RNScreens', :podspec => "#{prefix}/../react-native-screens/RNScreens.podspec"
#  pod 'react-native-pager-view', :podspec => "#{prefix}/../react-native-pager-view/react-native-pager-view.podspec"
#  pod 'RNVectorIcons', :podspec => "#{prefix}/../react-native-vector-icons/RNVectorIcons.podspec"
#  pod 'RNCAsyncStorage', :podspec => "#{prefix}/../@react-native-async-storage/async-storage/RNCAsyncStorage.podspec"
#  pod 'RNSVG', :podspec => "#{prefix}/../react-native-svg/RNSVG.podspec"
#  pod 'RNZipArchive', :podspec => "#{prefix}/../react-native-zip-archive/RNZipArchive.podspec"
#  pod 'RNDateTimePicker', :podspec => "#{prefix}/../@react-native-community/datetimepicker/RNDateTimePicker.podspec"
#  pod 'react-native-image-picker', :podspec => "#{prefix}/../react-native-image-picker/react-native-image-picker.podspec"
#  pod 'BVLinearGradient', :podspec => "#{prefix}/../react-native-linear-gradient/BVLinearGradient.podspec"
#  pod 'RNCMaskedView', :podspec => "#{prefix}/../@react-native-masked-view/masked-view/RNCMaskedView.podspec"
#  pod 'RNFS', :podspec => "#{prefix}/../react-native-fs/RNFS.podspec"
#  pod 'react-native-webview', :podspec => "#{prefix}/../react-native-webview/react-native-webview.podspec"
#  pod 'ReactNativeART', :podspec => "#{prefix}/../@react-native-community/art/ReactNativeART.podspec"

  pod 'react-native-safe-area-context', :git => 'https://github.com/th3rdwave/react-native-safe-area-context.git', :tag => 'v3.4.1'
  pod 'RNScreens', :git => 'https://github.com/software-mansion/react-native-screens.git', :tag => '3.13.1'
  pod 'react-native-pager-view', :git => 'https://github.com/callstack/react-native-pager-view.git', :tag => 'v5.4.15'
  pod 'RNVectorIcons', :git => 'https://github.com/oblador/react-native-vector-icons.git', :tag => 'v9.1.0'
  pod 'RNCAsyncStorage', :git => 'https://github.com/react-native-async-storage/async-storage.git', :tag => 'v1.17.3'
  pod 'RNSVG', :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => 'v12.3.0'
  pod 'RNZipArchive', :git => 'https://github.com/mockingbot/react-native-zip-archive.git', :tag => 'v6.0.8'
  pod 'RNDateTimePicker', :git => 'https://github.com/react-native-community/datetimepicker', :tag => 'v6.1.3'
  pod 'react-native-image-picker', :git => 'https://github.com/react-native-image-picker/react-native-image-picker.git', :tag => 'v4.8.2'
  pod 'BVLinearGradient', :git => 'https://github.com/brentvatne/react-native-linear-gradient.git', :tag => 'v2.5.6'
  pod 'RNCMaskedView', :git => 'https://github.com/react-native-masked-view/masked-view.git', :tag => 'v0.2.6'
  pod 'RNFS', :git => 'https://github.com/itinance/react-native-fs', :tag => 'v2.20.0'
  pod 'react-native-webview', :git => 'https://github.com/react-native-webview/react-native-webview.git', :tag => 'v11.18.2'
  pod 'ReactNativeART', :git => 'https://github.com/react-native-community/art.git', :tag => 'v1.2.0'
  pod 'RNReanimated', :git => 'https://github.com/software-mansion/react-native-reanimated', :tag => '2.8.0'

  pod 'No1Sdk', :path => '../'
  pod 'BSDiff'

end

