#use_frameworks!

platform :ios, '11.0'

target 'No1Sdk_Example' do

  prefix = "./No1SdkLib/node_modules/react-native"

  pod 'FBLazyVector', :path => "#{prefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{prefix}/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{prefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{prefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{prefix}/"
  pod 'React-Core', :path => "#{prefix}/"
  pod 'React-CoreModules', :path => "#{prefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{prefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{prefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{prefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{prefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{prefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{prefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{prefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{prefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{prefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{prefix}/"

  pod 'React-cxxreact', :path => "#{prefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{prefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{prefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{prefix}/ReactCommon/jsinspector"
  pod 'React-callinvoker', :path => "#{prefix}/ReactCommon/callinvoker"
  pod 'React-runtimeexecutor', :path => "#{prefix}/ReactCommon/runtimeexecutor"
  pod 'React-perflogger', :path => "#{prefix}/ReactCommon/reactperflogger"
  pod 'React-logger', :path => "#{prefix}/ReactCommon/logger"
  pod 'ReactCommon/turbomodule/core', :path => "#{prefix}/ReactCommon"
  pod 'Yoga', :path => "#{prefix}/ReactCommon/yoga", :modular_headers => true

  pod 'DoubleConversion', :podspec => "#{prefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{prefix}/third-party-podspecs/glog.podspec"
  pod 'boost', :podspec => "#{prefix}/third-party-podspecs/boost.podspec"
  pod 'RCT-Folly', :podspec => "#{prefix}/third-party-podspecs/RCT-Folly.podspec"
  
  pod 'react-native-safe-area-context', :podspec => "#{prefix}/../react-native-safe-area-context/react-native-safe-area-context.podspec"
  pod 'RNScreens', :podspec => "#{prefix}/../react-native-screens/RNScreens.podspec"
  pod 'react-native-pager-view', :podspec => "#{prefix}/../react-native-pager-view/react-native-pager-view.podspec"
  pod 'RNVectorIcons', :podspec => "#{prefix}/../react-native-vector-icons/RNVectorIcons.podspec"
  pod 'RNCAsyncStorage', :podspec => "#{prefix}/../@react-native-async-storage/async-storage/RNCAsyncStorage.podspec"
  pod 'RNSVG', :podspec => "#{prefix}/../react-native-svg/RNSVG.podspec"
  pod 'RNZipArchive', :podspec => "#{prefix}/../react-native-zip-archive/RNZipArchive.podspec"
  pod 'RNDateTimePicker', :podspec => "#{prefix}/../@react-native-community/datetimepicker/RNDateTimePicker.podspec"
  pod 'react-native-image-picker', :podspec => "#{prefix}/../react-native-image-picker/react-native-image-picker.podspec"
  pod 'BVLinearGradient', :podspec => "#{prefix}/../react-native-linear-gradient/BVLinearGradient.podspec"
  pod 'RNCMaskedView', :podspec => "#{prefix}/../@react-native-masked-view/masked-view/RNCMaskedView.podspec"
  pod 'RNFS', :podspec => "#{prefix}/../react-native-fs/RNFS.podspec"
  pod 'react-native-webview', :podspec => "#{prefix}/../react-native-webview/react-native-webview.podspec"
  pod 'ReactNativeART', :podspec => "#{prefix}/../@react-native-community/art/ReactNativeART.podspec"

  pod 'No1Sdk', :path => '../'
  pod 'BSDiff'

end

